[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
package = "netlify-plugin-debug-cache"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    './build-dir/admin/',
    './admin/',
    './admin/index.html',
    './offline-plugin-app-shell-fallback/index.html',
    # By Glob pattern
    '**/**/child-one.html'
  ]